version: '3.8'

services:
  controller:
    image: jatinvpatil/naviclean:controller
    command: >
      ros2 launch naviclean_controller joystick_teleop_docker.launch.py
    # command: >
    #   sh -c "mkdir -p /root/.config/jstest-gtk && jstest-gtk"
    # sh -c "/etc/init.d/dbus start && /etc/init.d/bluetooth start && ros2 launch alphabot_controller joystick_teleop_docker.launch.py"
    # command: >
    #   sh -c "ros2 launch alphabot_controller joystick_teleop_docker.launch.py"
    network_mode: "host"
    privileged: true
    stdin_open: true
    restart: unless-stopped
    devices:
      - /dev/input/js*
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority
