TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.5
  min_vel_x: -0.25

  max_vel_theta:  0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 1.0 #The minimum rotational velocity allowed for the base while performing in-place rotations in radians/sec

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 0.25

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: false
  meter_scoring: true
   # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. 
   # Cells are assumed by default. New in navigation 1.3.1
   # Meter scoring set to true makes calculations based on meters and not on cells.
                      
# Forward Simulation Parameters
  sim_time: 2.5 #*
  vx_samples: 50 # The number of samples to use when exploring the x velocity space
  vtheta_samples: 50 # The number of samples to use when exploring the theta velocity space
  sim_granularity: 0.025 # The step size, in meters, to take between points on a given trajectory