obstacle_range: 3.0
raytrace_range: 8.0


#footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
robot_radius: 0.25

inflation_radius: 0.1
cost_scaling_factor: 1.2

map_type: costmap
observation_sources: scan
scan: {sensor_frame: ydlidar_1, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
