DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.25
  min_vel_x: 0.0 # set to negative, so that DWA planner can execute reverse motion in case of collision or recovery behaviour

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_theta: 0.6
  min_vel_theta: -0.6

  acc_lim_x: 0.4
  acc_lim_y: 0.0
  acc_lim_theta: 0.8

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 3.0 #*
  vx_samples: 15
  vy_samples: 0
  vth_samples: 100
  controller_frequency: 2.0

# Trajectory Scoring Parameters
  #meter_scoring: true
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
  forward_point_distance: 0.0
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true