shutdown_costmaps: false
controller_frequency: 2.0
planner_patience: 10.0
controller_patience: 10.0
conservative_reset_dist: 3.0
planner_frequency: 2.0
oscillation_timeout: 10.0
oscillation_distance: 0.1