joy_node:
  ros__parameters:
    device_id: 0
    # device_name: "X360 Controller"
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 4
    scale_linear:
      x: 0.3
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 1.5


    enable_button: 5
    enable_turbo_button: 4

    require_enable_button: true
