controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    naviclean_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

naviclean_controller:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    left_wheel_names  : ['base2left']
    right_wheel_names : ['base2right']

    # wheel_separation : 0.391                      #Wheel Seperation
    wheel_separation : 0.3602                     # Wheel Seperation change
    wheel_radius : 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    position_feedback: false #making it false uses velocity feedback, by default its true
    enable_odom_tf: true

    cmd_vel_timeout: 0.1

    # Publish limited velocity
    # publish_limited_velocity: true

    # # Publish wheel data
    # publish_wheel_data: true

    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.5  # m/s
        min_velocity           : -0.5 # m/s
        has_acceleration_limits: false
        max_acceleration       : 0.5  # m/s^2
        min_acceleration       : -0.5 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.2  # rad/s
        min_velocity           : -1.2 # rad/s
        has_acceleration_limits: false
        max_acceleration       : 0.6  # rad/s^2
        min_acceleration       : -0.6   # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3