name: NaviClean_CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - DockerFiles/NaviClean.Dockerfile
          - DockerFiles/RealSense.Dockerfile
          - DockerFiles/YDLidar.Dockerfile

        cache-name:
          - cache_naviclean
          - cache_realsense
          - cache_ydlidar

        image-tag:
          - naviclean
          - realsense
          - ydlidar

    env:
      IMAGE_NAME: jatinvpatil/naviclean

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      if: runner.os != 'Linux'

    - name: Set up Docker Buildx
      run: |
        docker buildx create --name mybuilder
        docker buildx use mybuilder
        docker buildx inspect --bootstrap

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      env:
        DOCKER_CLI_AARCH64_IMAGE: docker.io/docker/cli:24.0.6-dind-aarch64
      run: |
        docker buildx build \
            --platform=linux/arm64,linux/amd64 \
            --cache-from type=registry,ref=${{ env.IMAGE_NAME }}:${{ matrix.cache-name }} \
            --cache-to type=registry,ref=${{ env.IMAGE_NAME }}:${{ matrix.cache-name }},mode=max \
            --push \
            -t $IMAGE_NAME:${{ matrix.image-tag }} \
            -f ${{ matrix.dockerfile }} \
            .
